### ISSUE TITLE
autoenv blocks when changing from ~/a to ~/ab

### ISSUE THREAD

**Issue by ithinuel** [zpm-zsh/autoenv#14]
When changing to a directory whose name starts with the previous directory's name, autoenv is stuck in an infinite loop.

How to reproduce 
--------------------
```bash
mkdir a
mkdir ab
cd a
cd ../ab
```

**Comment by grigorii-horos** [comment]
@ithinuel Please check

**Comment by ithinuel** [comment]
@horosgrisa It created another issue. I can't reopen this one so I'll create a new.
