### ISSUE TITLE
autoenv blocks when entering a subdirectory

### ISSUE THREAD

**Issue by ithinuel** [zpm-zsh/autoenv#15]
# how to reproduce
## case 1
```shell
# new shell is ok
cd Documents
# cd never returns
```
## case 2
```shell
# new shell is ok
cd /usr
# everything is ok
cd include
# cd never returns
```

# Hint
I have added 
- `echo "out $_AUTOENV_OLDPATH"` on [line ][1]
- `echo "in  $_AUTOENV_OLDPATH"` on [line ][2]

and this is what is reported :
```
in  /usr/
in  /usr//
in  /usr///usr
in  /usr///usr/usr
in  /usr///usr/usr/usr
in  /usr///usr/usr/usr/usr
in  /usr///usr/usr/usr/usr/usr
in  /usr///usr/usr/usr/usr/usr/usr
...
```

[1]: https://github.com/zpm-zsh/autoenv/blob/f5352462644a71b44de1b81e8d991beb8cf3a4bb/autoenv.plugin.zsh#L78
[2]: https://github.com/zpm-zsh/autoenv/blob/f5352462644a71b44de1b81e8d991beb8cf3a4bb/autoenv.plugin.zsh#L89

**Comment by grigorii-horos** [comment]
@ithinuel Very intresting. But, I can't reproduce this 
https://asciinema.org/a/Yah4tHSdTCoBzpiW2z3uwUYty

**Comment by ithinuel** [comment]
I will probably try to play with the `IFS` var to handle paths as array.
```shell
join_path() { local IFS=/; echo "$*" }                                                                                                      
split_path() { local IFS=/; echo "$*" } # this does not break spaces in names. 
a=($(split_path 'ab cd/e/f/')) 
b=($(split_path '//gh i///j/k'))

echo $#a[@] $a[1]
join_path $a $b
```
results in :
```
4 ab cd
ab cd/e/f/gh i/j/k
```

I'll PR once it's fixed.
