### ISSUE TITLE
check_and_run:8: permission denied

### ISSUE THREAD

**Issue by maturanomx** [zpm-zsh/autoenv#18]
This is my `.env` file (similar as the example on README for NodeJS):

```
nvm use node
OLDPATH=$PATH
export PATH=`pwd`/node_modules/.bin:$PATH
```

When I enter to the directory I got the error this error:
```
> WARNING
> This is the first time you are about to source "/tmp/test/.env"

----------------

check_and_run:8: permission denied:

----------------

Are you sure you want to allow this? (y/N) y
N/A: version "N/A" is not yet installed.

You need to run "nvm install N/A" to install it before using it.
```

However, I'm able to `source` it without problem.
![screen shot 2018-03-27 at 7 07 11 pm](https://user-images.githubusercontent.com/5768813/38002902-26870d82-31f2-11e8-9ffd-639ca03b8ba7.png)

I don't have idea why 😕.

Version: zsh 5.4.2 (x86_64-apple-darwin17.3.0)

**Comment by grigorii-horos** [comment]
Mmm.. Very intresting

Please run `check_and_run .env` from directory `/tmp/test` and show me output.

**Comment by grigorii-horos** [comment]
Also create a simple file `.env`
```sh
echo it works
``` 
in your home directory and open new zsh session.

**Comment by maturanomx** [comment]
Interesting 🤔 ...

With the `.env` on home I have the same `permission denied` message, but the scrips is executed.

```
grep: /Users/maturano/.autoenv_authorized: No such file or directory
> WARNING
> This is the first time you are about to source "/Users/maturano/.env"

----------------

check_and_run:8: permission denied:

----------------

Are you sure you want to allow this? (y/N) y
it works
```

Running `check_and_run .env` manually run as expected (Note: I also try with the absolute path and works):
```
> WARNING
> This is the first time you are about to source ".env"

----------------

nvm use node
OLDPATH=$PATH
export PATH=`pwd`/node_modules/.bin:$PATH

----------------

Are you sure you want to allow this? (y/N) y
Now using node v8.10.0 (npm v5.6.0)
```

---
![screen shot 2018-03-28 at 10 51 04 am](https://user-images.githubusercontent.com/5768813/38044148-293cfd14-3276-11e8-8fb0-bbacb56dfe9b.png)

**Comment by grigorii-horos** [comment]
Line 8 in function `check_and_run` contain `whence pygmentize`, please execute it and show output. Also check if you have env variable $COLORS, execute `echo $COLORS`

```bash
whence pygmentize
echo $COLORS
````

**Comment by maturanomx** [comment]
```
$ whence pygmentize
/usr/local/bin/pygmentize

$ echo $COLORS
true
```

To be honest, I don't know where (and why) `$COLORS` is set 🤔 

---
![screen shot 2018-04-02 at 5 47 18 pm](https://user-images.githubusercontent.com/5768813/38220074-1c95da96-369e-11e8-83ff-f480b72c3dc6.png)

---
*EDIT*: Add information.

1. I can execute `pygmentize` from command line without problem.

2. Set `$COLORS` to `false` avoid the title error, but `nvm` still not working 😕 

![screen shot 2018-04-02 at 6 19 59 pm](https://user-images.githubusercontent.com/5768813/38220943-a09e945a-36a2-11e8-88c6-c4b857f80a90.png)

**Comment by maturanomx** [comment]
5d5cce04f1214ea3e8216815487d29ec116987a2 commit is what introduce this behaviour. Before that, works.

Maybe @ithinuel could help us here 😇 

---
**EDIT**: Correction... almost work. It is executing two times (on commit f535246)
![screen shot 2018-04-02 at 6 57 45 pm](https://user-images.githubusercontent.com/5768813/38221979-ecc2afd8-36a7-11e8-9ca0-259673ee9638.png)

**Comment by grigorii-horos** [comment]
I already have 2 issues with this commit. I temporarily revert repository in initial state

**Comment by grigorii-horos** [comment]
Please update plugin.

**Comment by ithinuel** [comment]
Hi, the error `N/A: version "N/A" is not yet installed` don't seem to be related to this as you invoke `nvm use stable`.
I'd say there's something else going on here.

I reproduced your issue (I was missing `pygmentize`).
I'm able to fix it by removing "whence" and calling `pygmentize` directly.

@horosgrisa what is this `whence` for here ?

**Comment by maturanomx** [comment]
@ithinuel 
> Hi, the error N/A: version "N/A" is not yet installed don't seem to be related to this as you invoke nvm use stable.
I'd say there's something else going on here.

The thing is, changes on this repository affect that behaviour. I'm able to source the `.env` and works fine. That's the behaviour that I expect of this plugin: just source the file in an automatic way.

By the error message I imagine is due to an environment change and it looks to me is pretty related to the "permission" error. Maybe create a sub-shell, sub-process... I don't know to be honest 😅 

@horosgrisa 
Right now from `master`, `nvm` is able to run:
![screen shot 2018-04-03 at 10 20 10 am](https://user-images.githubusercontent.com/5768813/38258709-cf7c4ba6-3728-11e8-82d7-e547ee31fe02.png)

It is executed two times. Should we create other ticket for that? Is that was 5d5cce0 tried to solve? 🤔

**Comment by ithinuel** [comment]
it was to solve #14 and later #15 and a couple other unreported issues.
I have this "double source" issue when I source the plugin for update.
The safe way is to close the terminal and open a new one.

What happens if you apply this patch 
```patch
diff --git a/autoenv.plugin.zsh b/autoenv.plugin.zsh
index 1b8ed9b..8a321dc 100755
--- a/autoenv.plugin.zsh
+++ b/autoenv.plugin.zsh
@@ -25,7 +25,7 @@ check_and_run(){
     echo -e "$fg_no_bold[green]----------------$reset_color"
     if hash pygmentize 2>/dev/null; then
       echo
-      `whence pygmentize` -f 256 -l shell -g "$1"
+      pygmentize -f 256 -l shell -g "$1"
     else
       echo -e "$fg_no_bold[green]"
       cat $1
```
to 86c98355ac28c93d92202d4fd9eea8036e6c9dcf ?

Does-it solve your issue ?

**Comment by grigorii-horos** [comment]
I reverted revert.

**Comment by maturanomx** [comment]
The "N/A" error apparently was a `nvm` issue. I updated it and works all now 🤦‍♂️ .

I'll close this issue. Thanks for everything 👍

**Comment by ithinuel** [comment]
@maturano That's a good news !
@horosgrisa Could you please restore master to this commit id : 86c98355ac28c93d92202d4fd9eea8036e6c9dcf where the PR #16 was actually merged :) (this will have the bonus of keeping a nice history)
The following commands should do the trick :
```bash
git checkout master
git rebase 86c98355ac28c93d92202d4fd9eea8036e6c9dcf 
git push -f
```

**EDIT:** Actually no, let me find a solution ⚔️ 
there we go :
```bash
git stash -u
git checkout master
git remote add ithinuel git@github.com:ithinuel/autoenv.git
git fetch ithinuel
git reset --hard 86c98355ac28c93d92202d4fd9eea8036e6c9dcf
git push -f
```
