### ISSUE TITLE
Consider using .env.local before .env

### ISSUE THREAD

**Issue by matthewmorek** [zpm-zsh/autoenv#20]
For a lot of modern web projects each developer keeps their respective environment variables stored locally, usually in a form of `.env.local` or `.env.*.local`.

Each of these files is added to `.gitignore` to prevent committing stuff such as API keys or other environment variables specific to a project to the repository in a `.env`, as this file is often added to the filesystem before deployment process commences.

It would be great if the plugin considered sourcing `.env.*.local` or `.env.local` before `.env` to make sure creators of these project can benefit from this plugin while developing their software locally.

**Comment by grigorii-horos** [comment]
You said interesting thing, but `.env` file really isn't shell script. Its format is compatible with shell, but variables isn't exported and only available from current shell session and no one of child programs can't access these vars. Its isn't big problem, sometimes it is even useful, but it restricts users, they cannot use all possibilities of shell syntax. 

My solution is change the default name from `.env` to `.in` and I'll do it soon. In `.in` file you will be able to write something like `source .env*` ant this will not conflict with `.env` files form web projects.

**Comment by matthewmorek** [comment]
You're right, not every `.env` is a shell script, which might prove problematic. I'm looking forward to this update, though since it'll make my life incredibly easy. :+1:
