### ISSUE TITLE
How to reuse configuration for siblling projects?

### ISSUE THREAD

**Issue by piether** [zpm-zsh/autoenv#21]
Hi,

I have several node projects living as sub directories in one directory. I created a `.in` file in this parent directory to set the `PATH`.

This setup works fine if I `cd` from outside of the parent directory into a project directory. But if I navigate within the project directories (which I do quite often), the script is not executed. (Which is the behavior as specified in the README.) But this means I end up with a PATH still pointing to the `node_modules` of the project where I came from.

Is there a better solution without having to specify an `.in` file in each project?

Thanks in advance

**Comment by grigorii-horos** [comment]
Mmm... Very interesting.
For example, I have `~/Projects/node`, and `.in` file in `~/Projects`. When I execute `cd ~/Projects/node`, this plugin execute `.in` file.
Can you provide your dir structure, and `.in` file?

**Comment by piether** [comment]
Here's a concrete example:
```
$ tree test/
test/
├── project-a
└── project-b

2 directories, 0 files
$ cat test/.in
echo "Adding $PWD/node_modules/bin to the PATH"
$ cd test/project-a 
Adding /home/pieter/test/project-a/node_modules/bin to the PATH
$ cd ../project-b
$ 
```

Nothing happens when I `cd ../project-b` while what I would like to happen is that it would execute the test/.in file again.

**Comment by grigorii-horos** [comment]
@piether Are you sure that you need this behaviour? You already have `$PWD/node_modules/bin` in your $PATH, and sourcing this file again will produce duplicates in your $PATH.

**Comment by piether** [comment]
But the value of $PWD is different when I change directories, so the expression needs to be re-evaluated, no? I didn't bother including an .out file but I would avoid duplicates in the PATH that way.

Here's an even more elaborated example of my problem:

test/.in:
```
echo "Adding $PWD/node_modules/bin to the PATH"
export PATH=$PWD/node_modules/bin:$PATH
echo "New PATH: $PATH" 
```

```
$ tree test/
test/
├── project-a
└── project-b
    └── node_modules
        └── bin
            └── grunt

4 directories, 1 file
$ cd test/project-a
Adding /home/pieter/test/project-a/node_modules/bin to the PATH
New PATH: /home/pieter/test/project-a/node_modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
$ cd ../project-b
$ grunt
zsh: command not found: grunt
$ cd /                                                                                                                                        127 ↵
$ cd ~/test/project-b
Adding /home/pieter/test/project-b/node_modules/bin to the PATH
New PATH: /home/pieter/test/project-b/node_modules/bin:/home/pieter/test/project-a/node_modules/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
$ grunt
$ 
```

So the project-b/bin directory is only on the PATH after I `cd /` and then go back into it.

**Comment by grigorii-horos** [comment]
~@piether I understand you. It's a bug in the plugin. For file `~/Projects/.in`, when you execute `cd ~/Projects/project`, `$PWD` need to be `~/Projects`, but not `~/Projects/project`~

**Comment by piether** [comment]
After thinking about it once more, I conclude:
- you can put common stuff in parent directory `.in` and `.out` files that are not related to the exact location you `cd` into. E.g. an `AWS_PROFILE` for all projects for a certain customer
- if you want to set something that is related to the exact location, you need an explicit `.in` and `.out` in each directory where you want this behaviour.

**Comment by grigorii-horos** [comment]
@piether I make a mistake in my comment. it's normal behaviour of $PWD. Instead of using $PWD in `.in` files, you need to use `$(dirname $0)/your_path_with_bin`. So, you can use something like this 
```sh
for node_path in $(dirname $0)/*/node_modules/.bin; do
  export PATH=$PATH:$node_path
done
```
