### ISSUE TITLE
The location of the Zsh Plugin Standard has changed

### ISSUE THREAD

**Issue by ctrueden** [zpm-zsh/autoenv#28]
I noticed that this plugin (and probably others in this org) [includes a link](https://github.com/zpm-zsh/autoenv/blob/7c43e79affb8e41a6d34036ce44489910e7b5510/autoenv.plugin.zsh#L4) to the Zsh Plugin Standard at `http://zdharma.org/Zsh-100-Commits-Club/Zsh-Plugin-Standard.html`. But that URL is defunct now. I found a newer functional URL for the standard at https://z-shell.github.io/zsh-plugin-assessor/Zsh-Plugin-Standard. Note also that it seems the standard has now changed: the recommended `0=` definition is more complex now. Just wanted to give you a heads up. See also ohmyzsh/ohmyzsh#10518.

**Comment by grigorii-horos** [comment]
Hey @ctrueden . I know about this, and I have in plan to change this link in all my plugins. I will do this soon

**Comment by grigorii-horos** [comment]
@ctrueden Done!
