### ISSUE TITLE
$1 is passed to .env files

### ISSUE THREAD

**Issue by Nagasaki45** [zpm-zsh/autoenv#3]
Bash function arguments are passed to the sourced .env and .out scripts. For example:

```
➜  ~  ls -a test_autoenv
.  ..  .env
➜  ~  cat test_autoenv/.env 
echo "$1"
➜  ~  cd test_autoenv 
/home/nagasaki45/test_autoenv/.env
➜  test_autoenv  
```

More info about this behavior can be found [here](http://stackoverflow.com/questions/17361966/source-a-file-within-a-function-takes-function-parameters)

Specifically, it breaks [activation and deactivation](http://conda.pydata.org/docs/using/envs.html#change-environments-activate-deactivate) of conda environments. For example, I have a conda environment named `conda_autoenv`, which usually activated and deactivated using `source activate conda_autoenv` and `source deactivate`. Here is the bug:

```
➜  ~  ls -a test_autoenv 
.  ..  .env  .out
➜  ~  cat test_autoenv/.env 
source activate conda_autoenv
➜  ~  cat test_autoenv/.out 
source deactivate
➜  ~  cd test_autoenv 
discarding /home/nagasaki45/miniconda3/bin from PATH
prepending /home/nagasaki45/miniconda3/envs/conda_autoenv/bin to PATH
Error: too many arguments.
(conda_autoenv)➜  test_autoenv  cd ..
Error: too many arguments.
(conda_autoenv)➜  ~ 
```

Notice environment **was** activated, after all. However, the deactivation failed.

A possible solution I found, based on [this answer in stackoverflow](http://stackoverflow.com/a/17362498/1224456), can be found at https://github.com/Nagasaki45/autoenv/tree/better_source. With the proposed solution:

```
➜  ~  cd test_autoenv
discarding /home/nagasaki45/miniconda3/bin from PATH
prepending /home/nagasaki45/miniconda3/envs/conda_autoenv/bin to PATH
discarding /home/nagasaki45/miniconda3/envs/conda_autoenv/bin from PATH
(conda_autoenv)➜  test_autoenv  which python
/home/nagasaki45/miniconda3/envs/conda_autoenv/bin/python
(conda_autoenv)➜  test_autoenv  cd ..
discarding /home/nagasaki45/miniconda3/envs/conda_autoenv/bin from PATH
➜  ~
```

There are still issues with this solution, which I'm unable to understand. See the 3rd line after cd to the test_autoenv directory - it looks like the environment is not working as expected. On the other hand working in that envirnment is fine, everything works as expected.

**Comment by grigorii-horos** [comment]
Oops... Very interesting problem, I fixed this with your solution.

**Comment by Nagasaki45** [comment]
Thanks for the fast response!
