### ISSUE TITLE
bat pager interferes with output

### ISSUE THREAD

**Issue by baodrate** [zpm-zsh/autoenv#30]
When the contents of `.in` or `.out` are longer than the current terminal window, `bat`'s pager activates, preventing the user from seeing the prompt. And when the user leaves the pager the code excerpt shown is empty, e.g.:

```
> WARNING
> This is the first time you are about to source "/tmp/autoenv/.in"

----------------

----------------

Are you sure you want to allow this? (y/N)
```

Consider adding `-P` (i.e. `--paging=never`) to the `bat` options:
https://github.com/zpm-zsh/autoenv/blob/0dc14a4951990e8aef588e335aac43cca6708ea7/functions/autoenv_check_and_run#L11

**Comment by grigorii-horos** [comment]
@qubidt Hey! Thanks for the issue. Fixed in the new commit, please update plugin
